### ISSUE TITLE
Using Grove Port for UART

### ISSUE THREAD

**Issue by PlastiBots** [Xinyuan-LilyGO/T-RGB#14]
I want to use Grove port for UART and wondering if there's a way to do this?    I have a CAN BUS unit with Grove connector (TX,RX,3v3,GND) but it seems the T-RGB has mapped the pins on it's grove connector using I2C (GND, SCL,SDA,3v3).  Any way to re-map these pins for UART use?  Else, are there any other free pins that I can use for UART?

**Comment by mmMicky** [comment]
ESP32-S3 pins can be mapped arbitrarily.

**Comment by PlastiBots** [comment]
Been trying that and still can't get it working.   Tried SoftwareSerial, HardwareSerial etc.    The below sketch worked using SoftwareSerial on an Arduino Nano.  Tried to modify for the T-RGB using HardwareSerial, then SoftwareSerial but it does not want to work. I'm using a [Serial CAN BUS ODBII](https://docs.longan-labs.cc/1030001/#work-with-arduino) module connected to the Grove port.  RX TX GND 3v3.   

`#include <Arduino.h>
#include <Serial_CAN_Module.h>
//#include <SoftwareSerial.h>
//#include <HardwareSerial.h>


//HardwareSerial mySerial(1); // for UART1, leaves standard UART0 alone for debug output via USB/serial bridge
//HardwareSerial ESP32Serial1(1);
//Serial_CAN mySerial;
//#define can mySerial


Serial_CAN can;

#define STANDARD_CAN_11BIT      1       // That depands on your car. some 1 some 0. 

#if STANDARD_CAN_11BIT
unsigned long mask[4] = 
{
    0, 0x7FC,                // ext, maks 0
    0, 0x7FC,                // ext, mask 1
};

unsigned long filt[12] = 
{
    0, 0x7E8,                // ext, filt 0
    0, 0x7E8,                // ext, filt 1
    0, 0x7E8,                // ext, filt 2
    0, 0x7E8,                // ext, filt 3
    0, 0x7E8,                // ext, filt 4
    0, 0x7E8,                // ext, filt 5
};

#else
unsigned long mask[4] =
{
    1, 0x1fffffff,               // ext, maks 0
    1, 0x1fffffff,
};
 
unsigned long filt[12] =
{
    1, 0x18DAF110,                // ext, filt
    1, 0x18DAF110,                // ext, filt 1
    1, 0x18DAF110,                // ext, filt 2
    1, 0x18DAF110,                // ext, filt 3
    1, 0x18DAF110,                // ext, filt 4
    1, 0x18DAF110,                // ext, filt 5
};
#endif

void set_mask_filt()
{
    /*
     * set mask, set both the mask to 0x3ff
     */
MASK:
    if(can.setMask(mask))
    {
        Serial.println("set mask ok");
    }
    else
    {
        Serial.println("set mask fail, try again.");
        goto MASK;
    }
FILT:
    /*
     * set filter, we can receive id from 0x04 ~ 0x09
     */
    if(can.setFilt(filt))
    {
        Serial.println("set filt ok");
    }
    else 
    {
        Serial.println("set filt fail, try again");
        goto FILT;
    }
    
}

void setup()
{
    Serial.begin(115200);
    delay(5000);
    Serial.println("Trying...");
 
    //NANO  can.begin(2, 3, 38400);      // tx, rx  
    can.begin(8, 48, 38400);      // tx, rx  T-TGB
    //can.begin(48, 8, 38400);      // tx, rx  T-TGB
    //can.begin(0, 0, 38400);      // tx, rx  T-TGB
    set_mask_filt();
    Serial.println("Done!");

}

void loop()
{

}

// END FILE`

**Comment by mmMicky** [comment]
Try using "Seria2.begin(115200,SERIAR_8N1,TX,RX);"

**Comment by PlastiBots** [comment]
Ha!  Thx.  Got it working, I did try that but I was trying to figure out how to assign the instance of the hardware serial (mySerial in my code below) to Serial_CAN. Figured it out, sample below:  

```
#include <Arduino.h>
#include <Serial_CAN_Module.h>
#include <HardwareSerial.h>
HardwareSerial mySerial(1);
Serial_CAN can;

#define STANDARD_CAN_11BIT      1       // That depands on your car. some 1 some 0. 

#if STANDARD_CAN_11BIT
unsigned long mask[4] = 
{
    0, 0x7FC,                // ext, maks 0
    0, 0x7FC,                // ext, mask 1
};

unsigned long filt[12] = 
{
    0, 0x7E8,                // ext, filt 0
    0, 0x7E8,                // ext, filt 1
    0, 0x7E8,                // ext, filt 2
    0, 0x7E8,                // ext, filt 3
    0, 0x7E8,                // ext, filt 4
    0, 0x7E8,                // ext, filt 5
};

#else
unsigned long mask[4] =
{
    1, 0x1fffffff,               // ext, maks 0
    1, 0x1fffffff,
};
 
unsigned long filt[12] =
{
    1, 0x18DAF110,                // ext, filt
    1, 0x18DAF110,                // ext, filt 1
    1, 0x18DAF110,                // ext, filt 2
    1, 0x18DAF110,                // ext, filt 3
    1, 0x18DAF110,                // ext, filt 4
    1, 0x18DAF110,                // ext, filt 5
};
#endif

void set_mask_filt()
{
    /*
     * set mask, set both the mask to 0x3ff
     */
MASK:
    if(can.setMask(mask))
    {
        Serial.println("set mask ok");
    }
    else
    {
        Serial.println("set mask fail, try again.");
        goto MASK;
    }
FILT:
    /*
     * set filter, we can receive id from 0x04 ~ 0x09
     */
    if(can.setFilt(filt))
    {
        Serial.println("set filt ok");
    }
    else 
    {
        Serial.println("set filt fail, try again");
        goto FILT;
    }
    
}

void setup()
{
    Serial.begin(115200);
    delay(5000); //here for testing
    Serial.println("Trying...");
    mySerial.begin(38400,SERIAL_8N1,8,48);   //Serial2.begin(9600, SERIAL_8N1, RXD2, TXD2);
    can.begin(mySerial, 38400);      // tx, rx  T-TGB

    set_mask_filt();
    Serial.println("Done!");

}

void loop()
{
}
```

**Comment by criptych** [comment]
There is no Grove port on the T-RGB.  There is a Grove-shaped connector, but it is not Grove-compatible electrically.

**Comment by PlastiBots** [comment]
I did manage to get this working with a groove module. It was a while ago, but recall having to switch 2 wires with each other in the connector.  So, “Groove” with a caveat.
