### ISSUE TITLE
SD-card not working 

### ISSUE THREAD

**Issue by sandmen** [Xinyuan-LilyGO/T-RGB#17]
Hi,
I have tried several SD-cards.
Not one is working, or detected by the T-RGB !
Any hints?

**Comment by PlastiBots** [comment]
I suggest this be merged with #13 that I created earlier - I'm having the same issue.

**Comment by sandmen** [comment]
> I suggest this be merged with #13 that I created earlier - I'm having the same issue.

Workaround, you have to reduce the Clock for SPI.
I "just" set it to half, and the board detect SD-Cards.
There is already a patch around for the latest Arduino Framework.

**Comment by mmMicky** [comment]
if (!SD_MMC.begin("/sdcard", true, true)) {
    Serial.println("Card Mount Failed");
    return;
  }

**Comment by sandmen** [comment]
> 

Is for me not working... !
In SD_MMC.h 
SDMMC_FREQHIGHSPEED/2 is working...

have a look here
https://github.com/espressif/esp-idf/issues/8521

**Comment by PlastiBots** [comment]
@sandmen, where is this variable?  I looked at SD_MMC.h in my version of the ESP 2.0.4 package (C:\Users\Dave\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4\libraries\SD_MMC\src) and could not find an statement similar to the above.  SDMMC_FREQHIGHSPEED

**Comment by sandmen** [comment]
@PlastiBots I'm using Plaformio and this uses the version 2.0.5...
In the SD_MMC.c file, should be somewhere something like this 
**host.max_freq_khz = sdmmc_frequency;**
Have a look for that, and check, where the sdmmc_frequency is come from !
You can do this as well
**host.max_freq_khz = sdmmc_frequency/2;**

**Comment by PlastiBots** [comment]
Found it! Thx. Will give it a try.

**Comment by lewisxhe** [comment]
Has the problem been solved ? If you still have problems, please reopen
