### ISSUE TITLE
Display rotate 180 degree 

### ISSUE THREAD

**Issue by AlexNikTaran1987** [Xinyuan-LilyGO/T-RGB#22]
Hey, 
I tried rotate display on 180 degree and it's doesn't work. 
dispp->driver->sw_rotate = 1; 
dispp->driver->rotated = 2; 
and i have errors in runtime:
0x42039ca6: task_wdt_timeout_handling at /Users/aleksandrtaran/esp/esp-idf/components/esp_system/task_wdt.c:486 (discriminator 3)

0x42039e5c: task_wdt_isr at /Users/aleksandrtaran/esp/esp-idf/components/esp_system/task_wdt.c:586

0x403773aa: _xt_lowint1 at /Users/aleksandrtaran/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/xtensa_vectors.S:1117

0x42015100: draw_buf_flush at /Users/aleksandrtaran/DevelopmentX/T-RGB-main/example/esp-idf-example/T-RGB/managed_components/lvgl__lvgl/src/core/lv_refr.c:989

have you any ideas?

**Comment by lewisxhe** [comment]
I haven't used lvgl's rotation function yet, you can ask questions in the lvgl forum
