### ISSUE TITLE
Board/Route view with resister designations shown for hardware hacking

### ISSUE THREAD

**Issue by slastrina** [Xinyuan-LilyGO/T-RGB#24]
Hi, im looking for a board view that shows the resistor designations i.e. RU1/2/3 and R4/5/6
Reason i ask is i have removed the sd card slot and wired an spi device to the old mosi, miso, cs and sck pins, i now need to remove and bridge appropriate pins to restore connectivity but its difficult to identify which resistor pads i need to short circuit to restore connectivity to the mcu. 

Are you able to assist.
Thanks

**Comment by slastrina** [comment]
@LilyGO is the above request possible? an accompanying board layer routing diagram or a diagram indicating the resisters around the sd card

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/229395267-a2313771-4463-4efa-8447-b0511f4d458e.png)
![image](https://user-images.githubusercontent.com/22990954/229395822-83341b3f-9364-4bc8-afad-9e23ef1d7bef.png)

I hope it can help you

**Comment by slastrina** [comment]
Hi, yes that's a big help, though any chance you can provide the bottom layer as well, just so I can confirm where the vias are going

**Comment by lewisxhe** [comment]
I will provide it to you in two days, and I am currently on vacation

**Comment by slastrina** [comment]
No rush, thanks for your help, enjoy your holiday

**Comment by lewisxhe** [comment]
![image](https://user-images.githubusercontent.com/22990954/230537991-0e367d6f-7741-42ae-afb9-b76c08812a65.png)

**Comment by slastrina** [comment]
Thats a big help, really appreciate it
