### ISSUE TITLE
Where is the 8MB PSRAM?

### ISSUE THREAD

**Issue by krupis** [Xinyuan-LilyGO/T-RGB#33]
Hello. I want to understand where is 8MB PSRAM chip located? I have been analyzing schematic:
https://github.com/Xinyuan-LilyGO/T-RGB/blob/main/schematic/T-RGB.pdf
and it does not seem to be on it.

I think the provided schematic is not full

**Comment by lewisxhe** [comment]
![image](https://github.com/Xinyuan-LilyGO/T-RGB/assets/22990954/b3481b25-a4f2-4c13-b7d3-ea311819c471)
